%%{init: {'classDiagram': {'layoutDirection': 'TB'}}}%%
classDiagram
    class GameManager {
        +money number
        +addMoney(amount) void
        +spendMoney(amount) boolean
        +resetMoney() void
        +instance GameManager
    }